"""Initial fresh database

Revision ID: c7ec05cd28b7
Revises: 
Create Date: 2026-03-03 14:40:43.499127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ec05cd28b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=False),
    sa.Column('is_promo_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('name_website', sa.String(length=255), nullable=True),
    sa.Column('url_website', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('username_magazine', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazines_promo_code'), 'magazines', ['promo_code'], unique=True)
    op.create_table('my_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('last_post_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_sessions_token'), 'payment_sessions', ['token'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=10), server_default='telegram', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payments_telegram_id'), 'payments', ['telegram_id'], unique=False)
    op.create_table('tech_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('magazine_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('last_post_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=150), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('magazine_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('subscribed_to_author', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('wb_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stroller_model', sa.String(length=50), nullable=True),
    sa.Column('first_to_feedback', sa.String(length=20), nullable=True),
    sa.Column('service_registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requests_left', sa.Integer(), nullable=False),
    sa.Column('closed_menu_flag', sa.Boolean(), nullable=False),
    sa.Column('first_catalog_request', sa.Boolean(), nullable=False),
    sa.Column('first_info_request', sa.Boolean(), nullable=False),
    sa.Column('show_intro_message', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    op.create_table('user_quiz_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_once', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quiz_profiles_user_id'), 'user_quiz_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quiz_profiles_user_id'), table_name='user_quiz_profiles')
    op.drop_table('user_quiz_profiles')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('magazine_channels')
    op.drop_table('tech_channels')
    op.drop_index(op.f('ix_payments_telegram_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_sessions_token'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    op.drop_table('my_channels')
    op.drop_index(op.f('ix_magazines_promo_code'), table_name='magazines')
    op.drop_table('magazines')
    # ### end Alembic commands ###
